create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  telegram_id text unique,
  rating numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  parent_id bigint references public.categories(id) on delete set null,
  sort_order integer not null default 0
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  seller_id bigint not null references public.users(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  slug text,
  description text not null,
  price integer not null check (price >= 0),
  currency text not null default 'BYN',
  status text not null default 'active' check (status in ('draft', 'active', 'sold', 'archived', 'deleted')),
  city text,
  views integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_listings_status_created on public.listings(status, created_at desc);
create index if not exists idx_listings_category on public.listings(category_id);
create index if not exists idx_listings_price on public.listings(price);
create index if not exists idx_listings_seller on public.listings(seller_id);
create index if not exists idx_listings_slug on public.listings(slug);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_listings_updated_at on public.listings;
create trigger trg_listings_updated_at
before update on public.listings
for each row
execute function public.touch_updated_at();

create table if not exists public.images (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  url text not null,
  alt_text text,
  sort_order integer not null default 0
);

create index if not exists idx_images_listing on public.images(listing_id, sort_order);

create table if not exists public.favorites (
  user_id bigint not null references public.users(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

insert into public.categories (name, slug, parent_id)
values
  ('Электроника', 'electronics', null),
  ('Авто и мото', 'auto', null),
  ('Дом и ремонт', 'home-repair', null),
  ('Одежда', 'clothing', null)
on conflict (slug) do nothing;

insert into public.categories (name, slug, parent_id)
select child.name, child.slug, parent.id
from (
  values
    ('Мобильные телефоны', 'mobile-phones', 'electronics'),
    ('Компьютеры и комплектующие', 'computers-parts', 'electronics'),
    ('Ремонт техники', 'device-repair', 'electronics'),
    ('Запчасти', 'auto-parts', 'auto'),
    ('Шины и диски', 'tires-wheels', 'auto'),
    ('Инструменты', 'tools', 'home-repair'),
    ('Мебель', 'furniture', 'home-repair'),
    ('Мужская одежда', 'mens-clothing', 'clothing'),
    ('Женская одежда', 'womens-clothing', 'clothing')
) as child(name, slug, parent_slug)
join public.categories parent on parent.slug = child.parent_slug
on conflict (slug) do nothing;
